const images = {
    logo: require('./Logo.png'),
    simpleLogo: require('./simpleLogo.png'),
    search: require('./search.png'),
    hamburg: require('./3lines.png'),
    skewImg1: require('./skewImg.png'),
    skewImg2: require("./skewImg1.png"),
    skewImg3: require("./skewImg2.png"),
    browser: require("./browser.png"),
    appDev: require("./appDev.png"),
    devSol: require("./devSol.png"),
    services1: require("./services1.png"),
    services2: require("./services2.png"),
    services3: require("./services3.png"),
    services4: require("./services4.png"),
    devSol1: require("./devSol1.png"),
    devSol2: require("./devSol2.png"),
    devSol3: require("./devSol3.png"),
    devSol4: require("./devSol4.png"),
    uiux1: require("./uixu1.png"),
    uiux2: require("./uixu2.png"),
    uiux3: require("./uixu3.png"),
    uiux4: require("./uixu4.png"),
    appDev1: require("./appDev1.png"),
    appDev2: require("./appDev2.png"),
    appDev3: require("./appDev3.png"),
    appDev4: require("./appDev4.png"),
    webDev1: require("./webDev1.png"),
    webDev2: require("./webDev2.png"),
    webDev3: require("./webDev3.png"),
    webDev4: require("./webDev4.png"),
    uiux: require("./uiux_icon.png"),
    more: require("./more.png"),
    bulbs: require("./3bulbs.png"),
    tickSearch: require("./tickSearch.png"),
    coinsBag: require("./coinsBag.png"),
    skewImg4: require("./Vector 24.png"),
    skewImg5: require("./Vector 21.png"),
    serviceSkew: require("./Vector 1.png"),
    portfolioSkew: require("./Vector 27.png"),
    contactSkew: require("./Vector 9.png"),
}
export default images